#!/usr/bin/perl -w

use strict;
use warnings;
use LWP::Simple;

#
my $url = shift || die "Please provide initial source";
my $max = 10;

my $html_page = get($url);

#array to store the urls
my @urls;
while ($html_page =~ s/(http:\/\/\S+)[">]//) {
 push @urls, $1;
}

mkdir "web", 0755;

open(my $file, ">", "web/url.map") || die "can't open file";
my $count = 0;

for (my $i=0; $i<$max; $i++) {
 my $src = $urls[int(rand($#urls+1))];
 my $code = getstore($src, "web/web$count.html");
 if ($code == 200){
  print "Success";
 }
 else{
  print "Failure";
  print $code;
 }
 print $file "$count \t $src \n";
 print STDERR "getting $count from $src\n";
 $count++;
 }

close $file;
